USE [MAAR_CUBE]
GO

/****** Object:  Table [dbo].[Property]    Script Date: 7/19/2019 12:01:06 AM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Property](
	[created_at] [time](7) NULL,
	[updated_at] [time](7) NULL,
	[id] [int] IDENTITY(1,1) NOT NULL,
	[AboveGradeFinishedArea] [decimal](30, 10) NULL,
	[AboveGradeFinishedAreaSource] varchar(max) NULL,
	[AboveGradeFinishedAreaUnits] varchar(max) NULL,
	[AccessCode] varchar(max) NULL,
	[AccessibilityFeatures] varchar(max) NULL,
	[AdditionalParcelsDescription] varchar(max) NULL,
	[AdditionalParcelsYN] [bit] NULL,
	[AnchorsCoTenants] varchar(max) NULL,
	[Appliances] varchar(max) NULL,
	[ApprovalStatus] varchar(max) NULL,
	[ArchitecturalStyle] varchar(max) NULL,
	[AssociationAmenities] varchar(max) NULL,
	[AssociationFee] [decimal](30, 10) NULL,
	[AssociationFee2] [decimal](30, 10) NULL,
	[AssociationFee2Frequency] varchar(max) NULL,
	[AssociationFeeFrequency] varchar(max) NULL,
	[AssociationFeeIncludes] varchar(max) NULL,
	[AssociationName] varchar(max) NULL,
	[AssociationName2] varchar(max) NULL,
	[AssociationPhone] varchar(max) NULL,
	[AssociationPhone2] varchar(max) NULL,
	[AssociationYN] [bit] NULL,
	[AttachedGarageYN] [bit] NULL,
	[AvailabilityDate] [date] NULL,
	[Basement] varchar(max) NULL,
	[BathroomsFull] [decimal](30, 10) NULL,
	[BathroomsHalf] [decimal](30, 10) NULL,
	[BathroomsOneQuarter] [decimal](30, 10) NULL,
	[BathroomsPartial] [decimal](30, 10) NULL,
	[BathroomsThreeQuarter] [decimal](30, 10) NULL,
	[BathroomsTotalInteger] [decimal](30, 10) NULL,
	[BedroomsPossible] [decimal](30, 10) NULL,
	[BedroomsTotal] [decimal](30, 10) NULL,
	[BelowGradeFinishedArea] [decimal](30, 10) NULL,
	[BelowGradeFinishedAreaSource] varchar(max) NULL,
	[BelowGradeFinishedAreaUnits] varchar(max) NULL,
	[BodyType] varchar(max) NULL,
	[BuilderModel] varchar(max) NULL,
	[BuilderName] varchar(max) NULL,
	[BuildingAreaSource] varchar(max) NULL,
	[BuildingAreaTotal] [decimal](30, 10) NULL,
	[BuildingAreaUnits] varchar(max) NULL,
	[BuildingFeatures] varchar(max) NULL,
	[BuildingName] varchar(max) NULL,
	[BusinessName] varchar(max) NULL,
	[BusinessType] varchar(max) NULL,
	[BuyerAgencyCompensation] varchar(max) NULL,
	[BuyerAgencyCompensationType] varchar(max) NULL,
	[BuyerAgentAOR] varchar(max) NULL,
	[BuyerAgentCellPhone] varchar(max) NULL,
	[BuyerAgentDesignation] varchar(max) NULL,
	[BuyerAgentDirectPhone] varchar(max) NULL,
	[BuyerAgentEmail] varchar(max) NULL,
	[BuyerAgentFax] varchar(max) NULL,
	[BuyerAgentFirstName] varchar(max) NULL,
	[BuyerAgentFullName] varchar(max) NULL,
	[BuyerAgentHomePhone] varchar(max) NULL,
	[BuyerAgentKey] varchar(max) NULL,
	[BuyerAgentKeyNumeric] [decimal](30, 10) NULL,
	[BuyerAgentLastName] varchar(max) NULL,
	[BuyerAgentMiddleName] varchar(max) NULL,
	[BuyerAgentMlsId] varchar(max) NULL,
	[BuyerAgentNamePrefix] varchar(max) NULL,
	[BuyerAgentNameSuffix] varchar(max) NULL,
	[BuyerAgentOfficePhone] varchar(max) NULL,
	[BuyerAgentOfficePhoneExt] varchar(max) NULL,
	[BuyerAgentPager] varchar(max) NULL,
	[BuyerAgentPreferredPhone] varchar(max) NULL,
	[BuyerAgentPreferredPhoneExt] varchar(max) NULL,
	[BuyerAgentStateLicense] varchar(max) NULL,
	[BuyerAgentTollFreePhone] varchar(max) NULL,
	[BuyerAgentURL] varchar(max) NULL,
	[BuyerAgentVoiceMail] varchar(max) NULL,
	[BuyerAgentVoiceMailExt] varchar(max) NULL,
	[BuyerFinancing] varchar(max) NULL,
	[BuyerOfficeAOR] varchar(max) NULL,
	[BuyerOfficeEmail] varchar(max) NULL,
	[BuyerOfficeFax] varchar(max) NULL,
	[BuyerOfficeKey] varchar(max) NULL,
	[BuyerOfficeKeyNumeric] [decimal](30, 10) NULL,
	[BuyerOfficeMlsId] varchar(max) NULL,
	[BuyerOfficeName] varchar(max) NULL,
	[BuyerOfficePhone] varchar(max) NULL,
	[BuyerOfficePhoneExt] varchar(max) NULL,
	[BuyerOfficeURL] varchar(max) NULL,
	[BuyerTeamKey] varchar(max) NULL,
	[BuyerTeamKeyNumeric] [decimal](30, 10) NULL,
	[BuyerTeamName] varchar(max) NULL,
	[CableTvExpense] [decimal](30, 10) NULL,
	[CancelationDate] [date] NULL,
	[CapRate] [decimal](30, 10) NULL,
	[CarportSpaces] [decimal](30, 10) NULL,
	[CarportYN] [bit] NULL,
	[CarrierRoute] varchar(max) NULL,
	[City] varchar(max) NULL,
	[CityRegion] varchar(max) NULL,
	[CloseDate] [date] NULL,
	[ClosePrice] [decimal](30, 10) NULL,
	[CoBuyerAgentAOR] varchar(max) NULL,
	[CoBuyerAgentCellPhone] varchar(max) NULL,
	[CoBuyerAgentDesignation] varchar(max) NULL,
	[CoBuyerAgentDirectPhone] varchar(max) NULL,
	[CoBuyerAgentEmail] varchar(max) NULL,
	[CoBuyerAgentFax] varchar(max) NULL,
	[CoBuyerAgentFirstName] varchar(max) NULL,
	[CoBuyerAgentFullName] varchar(max) NULL,
	[CoBuyerAgentHomePhone] varchar(max) NULL,
	[CoBuyerAgentKey] varchar(max) NULL,
	[CoBuyerAgentKeyNumeric] [decimal](30, 10) NULL,
	[CoBuyerAgentLastName] varchar(max) NULL,
	[CoBuyerAgentMiddleName] varchar(max) NULL,
	[CoBuyerAgentMlsId] varchar(max) NULL,
	[CoBuyerAgentNamePrefix] varchar(max) NULL,
	[CoBuyerAgentNameSuffix] varchar(max) NULL,
	[CoBuyerAgentOfficePhone] varchar(max) NULL,
	[CoBuyerAgentOfficePhoneExt] varchar(max) NULL,
	[CoBuyerAgentPager] varchar(max) NULL,
	[CoBuyerAgentPreferredPhone] varchar(max) NULL,
	[CoBuyerAgentPreferredPhoneExt] varchar(max) NULL,
	[CoBuyerAgentStateLicense] varchar(max) NULL,
	[CoBuyerAgentTollFreePhone] varchar(max) NULL,
	[CoBuyerAgentURL] varchar(max) NULL,
	[CoBuyerAgentVoiceMail] varchar(max) NULL,
	[CoBuyerAgentVoiceMailExt] varchar(max) NULL,
	[CoBuyerOfficeAOR] varchar(max) NULL,
	[CoBuyerOfficeEmail] varchar(max) NULL,
	[CoBuyerOfficeFax] varchar(max) NULL,
	[CoBuyerOfficeKey] varchar(max) NULL,
	[CoBuyerOfficeKeyNumeric] [decimal](30, 10) NULL,
	[CoBuyerOfficeMlsId] varchar(max) NULL,
	[CoBuyerOfficeName] varchar(max) NULL,
	[CoBuyerOfficePhone] varchar(max) NULL,
	[CoBuyerOfficePhoneExt] varchar(max) NULL,
	[CoBuyerOfficeURL] varchar(max) NULL,
	[CoListAgentAOR] varchar(max) NULL,
	[CoListAgentCellPhone] varchar(max) NULL,
	[CoListAgentDesignation] varchar(max) NULL,
	[CoListAgentDirectPhone] varchar(max) NULL,
	[CoListAgentEmail] varchar(max) NULL,
	[CoListAgentFax] varchar(max) NULL,
	[CoListAgentFirstName] varchar(max) NULL,
	[CoListAgentFullName] varchar(max) NULL,
	[CoListAgentHomePhone] varchar(max) NULL,
	[CoListAgentKey] varchar(max) NULL,
	[CoListAgentKeyNumeric] [decimal](30, 10) NULL,
	[CoListAgentLastName] varchar(max) NULL,
	[CoListAgentMiddleName] varchar(max) NULL,
	[CoListAgentMlsId] varchar(max) NULL,
	[CoListAgentNamePrefix] varchar(max) NULL,
	[CoListAgentNameSuffix] varchar(max) NULL,
	[CoListAgentOfficePhone] varchar(max) NULL,
	[CoListAgentOfficePhoneExt] varchar(max) NULL,
	[CoListAgentPager] varchar(max) NULL,
	[CoListAgentPreferredPhone] varchar(max) NULL,
	[CoListAgentPreferredPhoneExt] varchar(max) NULL,
	[CoListAgentStateLicense] varchar(max) NULL,
	[CoListAgentTollFreePhone] varchar(max) NULL,
	[CoListAgentURL] varchar(max) NULL,
	[CoListAgentVoiceMail] varchar(max) NULL,
	[CoListAgentVoiceMailExt] varchar(max) NULL,
	[CoListOfficeAOR] varchar(max) NULL,
	[CoListOfficeEmail] varchar(max) NULL,
	[CoListOfficeFax] varchar(max) NULL,
	[CoListOfficeKey] varchar(max) NULL,
	[CoListOfficeKeyNumeric] [decimal](30, 10) NULL,
	[CoListOfficeMlsId] varchar(max) NULL,
	[CoListOfficeName] varchar(max) NULL,
	[CoListOfficePhone] varchar(max) NULL,
	[CoListOfficePhoneExt] varchar(max) NULL,
	[CoListOfficeURL] varchar(max) NULL,
	[CommonWalls] varchar(max) NULL,
	[CommunityFeatures] varchar(max) NULL,
	[Concessions] varchar(max) NULL,
	[ConcessionsAmount] [decimal](30, 10) NULL,
	[ConcessionsComments] varchar(max) NULL,
	[ConstructionMaterials] varchar(max) NULL,
	[ContinentRegion] varchar(max) NULL,
	[Contingency] varchar(max) NULL,
	[ContingentDate] [date] NULL,
	[ContractStatusChangeDate] [date] NULL,
	[Cooling] varchar(max) NULL,
	[CoolingYN] [bit] NULL,
	[CopyrightNotice] varchar(max) NULL,
	[Country] varchar(max) NULL,
	[CountryRegion] varchar(max) NULL,
	[CountyOrParish] varchar(max) NULL,
	[CoveredSpaces] [decimal](30, 10) NULL,
	[CropsIncludedYN] [bit] NULL,
	[CrossStreet] varchar(max) NULL,
	[CultivatedArea] [decimal](30, 10) NULL,
	[CumulativeDaysOnMarket] [decimal](30, 10) NULL,
	[CurrentFinancing] varchar(max) NULL,
	[CurrentUse] varchar(max) NULL,
	[DOH1] varchar(max) NULL,
	[DOH2] varchar(max) NULL,
	[DOH3] varchar(max) NULL,
	[DaysOnMarket] [decimal](30, 10) NULL,
	[DevelopmentStatus] varchar(max) NULL,
	[DirectionFaces] varchar(max) NULL,
	[Directions] varchar(max) NULL,
	[Disclaimer] varchar(max) NULL,
	[Disclosures] varchar(max) NULL,
	[DistanceToBusComments] varchar(max) NULL,
	[DistanceToBusNumeric] [decimal](30, 10) NULL,
	[DistanceToBusUnits] varchar(max) NULL,
	[DistanceToElectricComments] varchar(max) NULL,
	[DistanceToElectricNumeric] [decimal](30, 10) NULL,
	[DistanceToElectricUnits] varchar(max) NULL,
	[DistanceToFreewayComments] varchar(max) NULL,
	[DistanceToFreewayNumeric] [decimal](30, 10) NULL,
	[DistanceToFreewayUnits] varchar(max) NULL,
	[DistanceToGasComments] varchar(max) NULL,
	[DistanceToGasNumeric] [decimal](30, 10) NULL,
	[DistanceToGasUnits] varchar(max) NULL,
	[DistanceToPhoneServiceComments] varchar(max) NULL,
	[DistanceToPhoneServiceNumeric] [decimal](30, 10) NULL,
	[DistanceToPhoneServiceUnits] varchar(max) NULL,
	[DistanceToPlaceofWorshipComments] varchar(max) NULL,
	[DistanceToPlaceofWorshipNumeric] [decimal](30, 10) NULL,
	[DistanceToPlaceofWorshipUnits] varchar(max) NULL,
	[DistanceToSchoolBusComments] varchar(max) NULL,
	[DistanceToSchoolBusNumeric] [decimal](30, 10) NULL,
	[DistanceToSchoolBusUnits] varchar(max) NULL,
	[DistanceToSchoolsComments] varchar(max) NULL,
	[DistanceToSchoolsNumeric] [decimal](30, 10) NULL,
	[DistanceToSchoolsUnits] varchar(max) NULL,
	[DistanceToSewerComments] varchar(max) NULL,
	[DistanceToSewerNumeric] [decimal](30, 10) NULL,
	[DistanceToSewerUnits] varchar(max) NULL,
	[DistanceToShoppingComments] varchar(max) NULL,
	[DistanceToShoppingNumeric] [decimal](30, 10) NULL,
	[DistanceToShoppingUnits] varchar(max) NULL,
	[DistanceToStreetComments] varchar(max) NULL,
	[DistanceToStreetNumeric] [decimal](30, 10) NULL,
	[DistanceToStreetUnits] varchar(max) NULL,
	[DistanceToWaterComments] varchar(max) NULL,
	[DistanceToWaterNumeric] [decimal](30, 10) NULL,
	[DistanceToWaterUnits] varchar(max) NULL,
	[DocumentsAvailable] varchar(max) NULL,
	[DocumentsChangeTimestamp] [datetime2](7) NULL,
	[DocumentsCount] [decimal](30, 10) NULL,
	[DoorFeatures] varchar(max) NULL,
	[DualVariableCompensationYN] [bit] NULL,
	[Electric] varchar(max) NULL,
	[ElectricExpense] [decimal](30, 10) NULL,
	[ElectricOnPropertyYN] [bit] NULL,
	[ElementarySchool] varchar(max) NULL,
	[ElementarySchoolDistrict] varchar(max) NULL,
	[Elevation] [decimal](30, 10) NULL,
	[ElevationUnits] varchar(max) NULL,
	[EntryLevel] [decimal](30, 10) NULL,
	[EntryLocation] varchar(max) NULL,
	[Exclusions] varchar(max) NULL,
	[ExistingLeaseType] varchar(max) NULL,
	[ExpirationDate] [date] NULL,
	[ExteriorFeatures] varchar(max) NULL,
	[FarmCreditServiceInclYN] [bit] NULL,
	[FarmLandAreaSource] varchar(max) NULL,
	[FarmLandAreaUnits] varchar(max) NULL,
	[Fencing] varchar(max) NULL,
	[FinancialDataSource] varchar(max) NULL,
	[FireplaceFeatures] varchar(max) NULL,
	[FireplaceYN] [bit] NULL,
	[FireplacesTotal] [decimal](30, 10) NULL,
	[Flooring] varchar(max) NULL,
	[FoundationArea] [decimal](30, 10) NULL,
	[FoundationDetails] varchar(max) NULL,
	[FrontageLength] varchar(max) NULL,
	[FrontageType] varchar(max) NULL,
	[FuelExpense] [decimal](30, 10) NULL,
	[Furnished] varchar(max) NULL,
	[FurnitureReplacementExpense] [decimal](30, 10) NULL,
	[GarageSpaces] [decimal](30, 10) NULL,
	[GarageYN] [bit] NULL,
	[GardnerExpense] [decimal](30, 10) NULL,
	[Gas] varchar(max) NULL,
	[GrazingPermitsBlmYN] [bit] NULL,
	[GrazingPermitsForestServiceYN] [bit] NULL,
	[GrazingPermitsPrivateYN] [bit] NULL,
	[GreenBuildingVerificationType] varchar(max) NULL,
	[GreenEnergyEfficient] varchar(max) NULL,
	[GreenEnergyGeneration] varchar(max) NULL,
	[GreenIndoorAirQuality] varchar(max) NULL,
	[GreenLocation] varchar(max) NULL,
	[GreenSustainability] varchar(max) NULL,
	[GreenVerification[Type]]Body] varchar(max) NULL,
	[GreenVerification[Type]]Metric] [decimal](30, 10) NULL,
	[GreenVerification[Type]]Rating] varchar(max) NULL,
	[GreenVerification[Type]]Source] varchar(max) NULL,
	[GreenVerification[Type]]Status] varchar(max) NULL,
	[GreenVerification[Type]]URL] varchar(max) NULL,
	[GreenVerification[Type]]Version] varchar(max) NULL,
	[GreenVerification[Type]]Year] [decimal](30, 10) NULL,
	[GreenWaterConservation] varchar(max) NULL,
	[GrossIncome] [decimal](30, 10) NULL,
	[GrossScheduledIncome] [decimal](30, 10) NULL,
	[HabitableResidenceYN] [bit] NULL,
	[Heating] varchar(max) NULL,
	[HeatingYN] [bit] NULL,
	[HighSchool] varchar(max) NULL,
	[HighSchoolDistrict] varchar(max) NULL,
	[HomeWarrantyYN] [bit] NULL,
	[HorseAmenities] varchar(max) NULL,
	[HorseYN] [bit] NULL,
	[HoursDaysOfOperation] varchar(max) NULL,
	[HoursDaysofOperationDescription] varchar(max) NULL,
	[Inclusions] varchar(max) NULL,
	[IncomeIncludes] varchar(max) NULL,
	[InsuranceExpense] [decimal](30, 10) NULL,
	[InteriorFeatures] varchar(max) NULL,
	[InternetAddressDisplayYN] [bit] NULL,
	[InternetAutomatedValuationDisplayYN] [bit] NULL,
	[InternetConsumerCommentYN] [bit] NULL,
	[InternetEntireListingDisplayYN] [bit] NULL,
	[IrrigationSource] varchar(max) NULL,
	[IrrigationWaterRightsAcres] [decimal](30, 10) NULL,
	[IrrigationWaterRightsYN] [bit] NULL,
	[LaborInformation] varchar(max) NULL,
	[LandLeaseAmount] [decimal](30, 10) NULL,
	[LandLeaseAmountFrequency] varchar(max) NULL,
	[LandLeaseExpirationDate] [date] NULL,
	[LandLeaseYN] [bit] NULL,
	[Latitude] [decimal](30, 10) NULL,
	[LaundryFeatures] varchar(max) NULL,
	[LeasableArea] [decimal](30, 10) NULL,
	[LeasableAreaUnits] varchar(max) NULL,
	[LeaseAmount] [decimal](30, 10) NULL,
	[LeaseAmountFrequency] varchar(max) NULL,
	[LeaseAssignableYN] [bit] NULL,
	[LeaseConsideredYN] [bit] NULL,
	[LeaseExpiration] [date] NULL,
	[LeaseRenewalCompensation] varchar(max) NULL,
	[LeaseRenewalOptionYN] [bit] NULL,
	[LeaseTerm] varchar(max) NULL,
	[Levels] varchar(max) NULL,
	[License1] varchar(max) NULL,
	[License2] varchar(max) NULL,
	[License3] varchar(max) NULL,
	[LicensesExpense] [decimal](30, 10) NULL,
	[ListAOR] varchar(max) NULL,
	[ListAgentAOR] varchar(max) NULL,
	[ListAgentCellPhone] varchar(max) NULL,
	[ListAgentDesignation] varchar(max) NULL,
	[ListAgentDirectPhone] varchar(max) NULL,
	[ListAgentEmail] varchar(max) NULL,
	[ListAgentFax] varchar(max) NULL,
	[ListAgentFirstName] varchar(max) NULL,
	[ListAgentFullName] varchar(max) NULL,
	[ListAgentHomePhone] varchar(max) NULL,
	[ListAgentKey] varchar(max) NULL,
	[ListAgentKeyNumeric] [decimal](30, 10) NULL,
	[ListAgentLastName] varchar(max) NULL,
	[ListAgentMiddleName] varchar(max) NULL,
	[ListAgentMlsId] varchar(max) NULL,
	[ListAgentNamePrefix] varchar(max) NULL,
	[ListAgentNameSuffix] varchar(max) NULL,
	[ListAgentOfficePhone] varchar(max) NULL,
	[ListAgentOfficePhoneExt] varchar(max) NULL,
	[ListAgentPager] varchar(max) NULL,
	[ListAgentPreferredPhone] varchar(max) NULL,
	[ListAgentPreferredPhoneExt] varchar(max) NULL,
	[ListAgentStateLicense] varchar(max) NULL,
	[ListAgentTollFreePhone] varchar(max) NULL,
	[ListAgentURL] varchar(max) NULL,
	[ListAgentVoiceMail] varchar(max) NULL,
	[ListAgentVoiceMailExt] varchar(max) NULL,
	[ListOfficeAOR] varchar(max) NULL,
	[ListOfficeEmail] varchar(max) NULL,
	[ListOfficeFax] varchar(max) NULL,
	[ListOfficeKey] varchar(max) NULL,
	[ListOfficeKeyNumeric] [decimal](30, 10) NULL,
	[ListOfficeMlsId] varchar(max) NULL,
	[ListOfficeName] varchar(max) NULL,
	[ListOfficePhone] varchar(max) NULL,
	[ListOfficePhoneExt] varchar(max) NULL,
	[ListOfficeURL] varchar(max) NULL,
	[ListPrice] [decimal](30, 10) NULL,
	[ListPriceLow] [decimal](30, 10) NULL,
	[ListTeamKey] varchar(max) NULL,
	[ListTeamKeyNumeric] [decimal](30, 10) NULL,
	[ListTeamName] varchar(max) NULL,
	[ListingAgreement] varchar(max) NULL,
	[ListingContractDate] [date] NULL,
	[ListingId] varchar(max) NULL,
	[ListingKey] varchar(max) NULL,
	[ListingKeyNumeric] [decimal](30, 10) NULL,
	[ListingService] varchar(max) NULL,
	[ListingTerms] varchar(max) NULL,
	[LivingArea] [decimal](30, 10) NULL,
	[LivingAreaSource] varchar(max) NULL,
	[LivingAreaUnits] varchar(max) NULL,
	[LockBoxLocation] varchar(max) NULL,
	[LockBoxSerialNumber] varchar(max) NULL,
	[LockBoxType] varchar(max) NULL,
	[Longitude] [decimal](30, 10) NULL,
	[LotDimensionsSource] varchar(max) NULL,
	[LotFeatures] varchar(max) NULL,
	[LotSizeAcres] [decimal](30, 10) NULL,
	[LotSizeArea] [decimal](30, 10) NULL,
	[LotSizeDimensions] varchar(max) NULL,
	[LotSizeSource] varchar(max) NULL,
	[LotSizeSquareFeet] [decimal](30, 10) NULL,
	[LotSizeUnits] varchar(max) NULL,
	[MLSAreaMajor] varchar(max) NULL,
	[MLSAreaMinor] varchar(max) NULL,
	[MainLevelBathrooms] [decimal](30, 10) NULL,
	[MainLevelBedrooms] [decimal](30, 10) NULL,
	[MaintenanceExpense] [decimal](30, 10) NULL,
	[MajorChangeTimestamp] [datetime2](7) NULL,
	[MajorChangeType] varchar(max) NULL,
	[Make] varchar(max) NULL,
	[ManagerExpense] [decimal](30, 10) NULL,
	[MapCoordinate] varchar(max) NULL,
	[MapCoordinateSource] varchar(max) NULL,
	[MapURL] varchar(max) NULL,
	[MiddleOrJuniorSchool] varchar(max) NULL,
	[MiddleOrJuniorSchoolDistrict] varchar(max) NULL,
	[MlsStatus] varchar(max) NULL,
	[MobileDimUnits] varchar(max) NULL,
	[MobileHomeRemainsYN] [bit] NULL,
	[MobileLength] [decimal](30, 10) NULL,
	[MobileWidth] [decimal](30, 10) NULL,
	[Model] varchar(max) NULL,
	[ModificationTimestamp] [datetime2](7) NULL,
	[NetOperatingIncome] [decimal](30, 10) NULL,
	[NewConstructionYN] [bit] NULL,
	[NewTaxesExpense] [decimal](30, 10) NULL,
	[NumberOfBuildings] [decimal](30, 10) NULL,
	[NumberOfFullTimeEmployees] [decimal](30, 10) NULL,
	[NumberOfLots] [decimal](30, 10) NULL,
	[NumberOfPads] [decimal](30, 10) NULL,
	[NumberOfPartTimeEmployees] [decimal](30, 10) NULL,
	[NumberOfSeparateElectricMeters] [decimal](30, 10) NULL,
	[NumberOfSeparateGasMeters] [decimal](30, 10) NULL,
	[NumberOfSeparateWaterMeters] [decimal](30, 10) NULL,
	[NumberOfUnitsInCommunity] [decimal](30, 10) NULL,
	[NumberOfUnitsLeased] [decimal](30, 10) NULL,
	[NumberOfUnitsMoMo] [decimal](30, 10) NULL,
	[NumberOfUnitsTotal] [decimal](30, 10) NULL,
	[NumberOfUnitsVacant] [decimal](30, 10) NULL,
	[OccupantName] varchar(max) NULL,
	[OccupantPhone] varchar(max) NULL,
	[OccupantType] varchar(max) NULL,
	[OffMarketDate] [date] NULL,
	[OffMarketTimestamp] [datetime2](7) NULL,
	[OnMarketDate] [date] NULL,
	[OnMarketTimestamp] [datetime2](7) NULL,
	[OpenParkingSpaces] [decimal](30, 10) NULL,
	[OpenParkingYN] [bit] NULL,
	[OperatingExpense] [decimal](30, 10) NULL,
	[OperatingExpenseIncludes] varchar(max) NULL,
	[OriginalEntryTimestamp] [datetime2](7) NULL,
	[OriginalListPrice] [decimal](30, 10) NULL,
	[OriginatingSystemID] varchar(max) NULL,
	[OriginatingSystemKey] varchar(max) NULL,
	[OriginatingSystemName] varchar(max) NULL,
	[OtherEquipment] varchar(max) NULL,
	[OtherExpense] [decimal](30, 10) NULL,
	[OtherParking] varchar(max) NULL,
	[OtherStructures] varchar(max) NULL,
	[OwnerName] varchar(max) NULL,
	[OwnerPays] varchar(max) NULL,
	[OwnerPhone] varchar(max) NULL,
	[Ownership] varchar(max) NULL,
	[OwnershipType] varchar(max) NULL,
	[ParcelNumber] varchar(max) NULL,
	[ParkManagerName] varchar(max) NULL,
	[ParkManagerPhone] varchar(max) NULL,
	[ParkName] varchar(max) NULL,
	[ParkingFeatures] varchar(max) NULL,
	[ParkingTotal] [decimal](30, 10) NULL,
	[PastureArea] [decimal](30, 10) NULL,
	[PatioAndPorchFeatures] varchar(max) NULL,
	[PendingTimestamp] [datetime2](7) NULL,
	[PestControlExpense] [decimal](30, 10) NULL,
	[PetsAllowed] varchar(max) NULL,
	[PhotosChangeTimestamp] [datetime2](7) NULL,
	[PhotosCount] [decimal](30, 10) NULL,
	[PoolExpense] [decimal](30, 10) NULL,
	[PoolFeatures] varchar(max) NULL,
	[PoolPrivateYN] [bit] NULL,
	[Possession] varchar(max) NULL,
	[PossibleUse] varchar(max) NULL,
	[PostalCity] varchar(max) NULL,
	[PostalCode] varchar(max) NULL,
	[PostalCodePlus4] varchar(max) NULL,
	[PowerProductionType] varchar(max) NULL,
	[PowerProduction[Type]] Annual] [decimal](30, 10) NULL,
	[PowerProduction[Type]]AnnualStatus] varchar(max) NULL,
	[PowerProduction[Type]]Size] [decimal](30, 10) NULL,
	[PowerProduction[Type]]YearInstall] [decimal](30, 10) NULL,
	[PreviousListPrice] [decimal](30, 10) NULL,
	[PriceChangeTimestamp] [datetime2](7) NULL,
	[PrivateOfficeRemarks] varchar(max) NULL,
	[PrivateRemarks] varchar(max) NULL,
	[ProfessionalManagementExpense] [decimal](30, 10) NULL,
	[PropertyAttachedYN] [bit] NULL,
	[PropertyCondition] varchar(max) NULL,
	[PropertySubType] varchar(max) NULL,
	[PropertyType] varchar(max) NULL,
	[PublicRemarks] varchar(max) NULL,
	[PublicSurveyRange] varchar(max) NULL,
	[PublicSurveySection] varchar(max) NULL,
	[PublicSurveyTownship] varchar(max) NULL,
	[PurchaseContractDate] [date] NULL,
	[RVParkingDimensions] varchar(max) NULL,
	[RangeArea] [decimal](30, 10) NULL,
	[RentControlYN] [bit] NULL,
	[RentIncludes] varchar(max) NULL,
	[RoadFrontageType] varchar(max) NULL,
	[RoadResponsibility] varchar(max) NULL,
	[RoadSurfaceType] varchar(max) NULL,
	[Roof] varchar(max) NULL,
	[RoomType] varchar(max) NULL,
	[Room[type]]Area] [decimal](30, 10) NULL,
	[Room[type]]AreaSource] varchar(max) NULL,
	[Room[type]]AreaUnits] varchar(max) NULL,
	[Room[type]]Description] varchar(max) NULL,
	[Room[type]]Dimensions] varchar(max) NULL,
	[Room[type]]Features] varchar(max) NULL,
	[Room[type]]Length] [decimal](30, 10) NULL,
	[Room[type]]LengthWidthSource] varchar(max) NULL,
	[Room[type]]LengthWidthUnits] varchar(max) NULL,
	[Room[type]]Level] varchar(max) NULL,
	[Room[type]]Width] [decimal](30, 10) NULL,
	[RoomsTotal] [decimal](30, 10) NULL,
	[SeatingCapacity] [decimal](30, 10) NULL,
	[SecurityFeatures] varchar(max) NULL,
	[SeniorCommunityYN] [bit] NULL,
	[SerialU] varchar(max) NULL,
	[SerialX] varchar(max) NULL,
	[SerialXX] varchar(max) NULL,
	[Sewer] varchar(max) NULL,
	[ShowingContactName] varchar(max) NULL,
	[ShowingContactPhone] varchar(max) NULL,
	[ShowingContactPhoneExt] varchar(max) NULL,
	[ShowingContactType] varchar(max) NULL,
	[ShowingInstructions] varchar(max) NULL,
	[SignOnPropertyYN] [bit] NULL,
	[Skirt] varchar(max) NULL,
	[SourceSystemID] varchar(max) NULL,
	[SourceSystemKey] varchar(max) NULL,
	[SourceSystemName] varchar(max) NULL,
	[SpaFeatures] varchar(max) NULL,
	[SpaYN] [bit] NULL,
	[SpecialLicenses] varchar(max) NULL,
	[SpecialListingConditions] varchar(max) NULL,
	[StandardStatus] varchar(max) NULL,
	[StateOrProvince] varchar(max) NULL,
	[StateRegion] varchar(max) NULL,
	[StatusChangeTimestamp] [datetime2](7) NULL,
	[Stories] [decimal](30, 10) NULL,
	[StoriesTotal] [decimal](30, 10) NULL,
	[StreetAdditionalInfo] varchar(max) NULL,
	[StreetDirPrefix] varchar(max) NULL,
	[StreetDirSuffix] varchar(max) NULL,
	[StreetName] varchar(max) NULL,
	[StreetNumber] varchar(max) NULL,
	[StreetNumberNumeric] [decimal](30, 10) NULL,
	[StreetSuffix] varchar(max) NULL,
	[StreetSuffixModifier] varchar(max) NULL,
	[StructureType] varchar(max) NULL,
	[SubAgencyCompensation] varchar(max) NULL,
	[SubAgencyCompensationType] varchar(max) NULL,
	[SubdivisionName] varchar(max) NULL,
	[SuppliesExpense] [decimal](30, 10) NULL,
	[SyndicateTo] varchar(max) NULL,
	[SyndicationRemarks] varchar(max) NULL,
	[TaxAnnualAmount] [decimal](30, 10) NULL,
	[TaxAssessedValue] [decimal](30, 10) NULL,
	[TaxBlock] varchar(max) NULL,
	[TaxBookNumber] varchar(max) NULL,
	[TaxExemptions] varchar(max) NULL,
	[TaxLegalDescription] varchar(max) NULL,
	[TaxLot] varchar(max) NULL,
	[TaxMapNumber] varchar(max) NULL,
	[TaxOtherAnnualAssessmentAmount] [decimal](30, 10) NULL,
	[TaxParcelLetter] varchar(max) NULL,
	[TaxStatusCurrent] varchar(max) NULL,
	[TaxTract] varchar(max) NULL,
	[TaxYear] [decimal](30, 10) NULL,
	[Telephone] varchar(max) NULL,
	[TenantPays] varchar(max) NULL,
	[Topography] varchar(max) NULL,
	[TotalActualRent] [decimal](30, 10) NULL,
	[Township] varchar(max) NULL,
	[TransactionBrokerCompensation] varchar(max) NULL,
	[TransactionBrokerCompensationType] varchar(max) NULL,
	[TrashExpense] [decimal](30, 10) NULL,
	[UnitNumber] varchar(max) NULL,
	[UnitTypeType] varchar(max) NULL,
	[UnitType[type]]ActualRent] [decimal](30, 10) NULL,
	[UnitType[type]]BathsTotal] [decimal](30, 10) NULL,
	[UnitType[type]]BedsTotal] [decimal](30, 10) NULL,
	[UnitType[type]]Description] varchar(max) NULL,
	[UnitType[type]]Furnished] varchar(max) NULL,
	[UnitType[type]]GarageAttachedYN] [bit] NULL,
	[UnitType[type]]GarageSpaces] [decimal](30, 10) NULL,
	[UnitType[type]]ProForma] [decimal](30, 10) NULL,
	[UnitType[type]]TotalRent] [decimal](30, 10) NULL,
	[UnitType[type]]UnitsTotal] [decimal](30, 10) NULL,
	[UnitsFurnished] varchar(max) NULL,
	[UnparsedAddress] varchar(max) NULL,
	[Utilities] varchar(max) NULL,
	[VacancyAllowance] [decimal](30, 10) NULL,
	[VacancyAllowanceRate] [decimal](30, 10) NULL,
	[Vegetation] varchar(max) NULL,
	[VideosChangeTimestamp] [datetime2](7) NULL,
	[VideosCount] [decimal](30, 10) NULL,
	[View] varchar(max) NULL,
	[ViewYN] [bit] NULL,
	[VirtualTourURLBranded] varchar(max) NULL,
	[VirtualTourURLUnbranded] varchar(max) NULL,
	[WalkScore] [decimal](30, 10) NULL,
	[WaterBodyName] varchar(max) NULL,
	[WaterSewerExpense] [decimal](30, 10) NULL,
	[WaterSource] varchar(max) NULL,
	[WaterfrontFeatures] varchar(max) NULL,
	[WaterfrontYN] [bit] NULL,
	[WindowFeatures] varchar(max) NULL,
	[WithdrawnDate] [date] NULL,
	[WoodedArea] [decimal](30, 10) NULL,
	[WorkmansCompensationExpense] [decimal](30, 10) NULL,
	[YearBuilt] [decimal](30, 10) NULL,
	[YearBuiltDetails] varchar(max) NULL,
	[YearBuiltEffective] [decimal](30, 10) NULL,
	[YearBuiltSource] varchar(max) NULL,
	[YearEstablished] [decimal](30, 10) NULL,
	[YearsCurrentOwner] [decimal](30, 10) NULL,
	[Zoning] varchar(max) NULL,
	[ZoningDescription] varchar(max) NULL,
	[LotSizeAreaRange] [int] NULL,
	[CurrentFinancingRemarks] [nchar](25) NULL,
	[YearBuiltRange] varchar(max) NULL,
	[Source] varchar(max) NULL,
	[UpdateDate] [datetime2](7) NULL,
 CONSTRAINT [Property_pkey] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO



